#!/usr/bin/perl
# written by peter stamfest <peter@stamfest.at>
#
# this file is in the public domain

use strict;
use utf8;
use open OUT => ':locale'; 

my $t = shift;

my $extchars = shift || '³²°üöä¹ÄÖÜ§';

open STDOUT, ">&1";

# use code b

my $i = 1;
my $d = chr(104 + 32);
my $s = 104;


foreach my $c (split //, $t) {
    $d .= $c;
    my $n = ord($c) - 32;
    $s += $n * $i;

#    print "$n ";

    $i++;
}

$s %= 103;
$d .= chr($s + 32);
$d .= chr(106 + 32);

my $d2 = "";

foreach my $c2 (split //, $d) {
    my $o = ord($c2);
    if ($o >= 128) {
	$d2 .= substr($extchars, $o - 128, 1);
    } else {
	$d2 .= $c2;
    }
}


utf8::upgrade($d2);
print "$d2\n";
